name:                LearnYouAHaskell
version:             0.1.0.0
github:              "https://github.com/bhongy"
license:             MIT
author:              "Thanik Bhongbhibhat"
maintainer:          "email@thanik.me"
copyright:           "2019 Thanik Bhongbhibhat"

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- lens
- random
- text

# library:
#   source-dirs: lib

executables:
  LearnYouAHaskell-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  LearnYouAHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
